version: '3.4'
services:
  mysql:
    image: mysql
    ports:
      - "33000:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: Alvaro987!
      MYSQL_ROOT_PASSWORD: Alvaro987!
      MYSQL_DATABASE: shelter