# MySQL
version: '3.4'
services:
  mysql_container:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
#      MYSQL_ROOT_PASSWORD: cavalos95TOMAS!
      MYSQL_DATABASE: storeproject
